import { CreateServicePackageDto } from '../dto/create-service-package.dto';

export const SERVICE_PACKAGE_SEED_DATA: CreateServicePackageDto[] = [
  {
    name: 'Tiệc cưới cao cấp',
    description:
      'Gói cưới trọn gói với trang trí premium, MC chuyên nghiệp, âm thanh ánh sáng và menu cao cấp.',
    basePrice: 85000000,
    imageUrl: 'https://images.unsplash.com/photo-1519741497674-611481863552',
    category: 'wedding',
    features: [
      'Trang trí sân khấu theo chủ đề',
      'MC dẫn chương trình chuyên nghiệp',
      'Âm thanh ánh sáng full set',
      'Bánh cưới và tháp ly',
    ],
    minGuests: 150,
    maxGuests: 500,
    serviceDuration: '4 tiếng',
    venueScope: 'Sảnh Grand Ballroom',
    defaultMenu: 'Wedding Premium Menu',
    isFeatured: true,
    isActive: true,
    sortOrder: 0,
  },
  {
    name: 'Đặt tiệc sinh nhật',
    description:
      'Gói sinh nhật linh hoạt cho gia đình và bạn bè, gồm trang trí, setup bánh và menu theo nhu cầu.',
    priceLabel: 'Liên hệ báo giá',
    imageUrl: 'https://images.unsplash.com/photo-1464349095431-e9a21285b5f3',
    category: 'celebration',
    features: [
      'Backdrop chụp hình theo concept',
      'Trang trí bong bóng và bàn gallery',
      'Âm nhạc nền phù hợp sự kiện',
    ],
    minGuests: 20,
    maxGuests: 120,
    serviceDuration: '3 tiếng',
    venueScope: 'Phòng riêng hoặc sân vườn',
    defaultMenu: 'Celebration Set Menu',
    isFeatured: true,
    isActive: true,
    sortOrder: 1,
  },
  {
    name: 'Hội nghị doanh nghiệp',
    description:
      'Giải pháp tổ chức hội nghị cho doanh nghiệp với màn hình LED, tea-break và đội ngũ vận hành onsite.',
    basePrice: 60000000,
    imageUrl: 'https://images.unsplash.com/photo-1511578314322-379afb476865',
    category: 'corporate',
    features: [
      'Setup sân khấu và màn hình LED',
      'Gói tea-break giữa giờ',
      'Kỹ thuật viên hỗ trợ xuyên suốt',
      'Bàn đón tiếp và check-in',
    ],
    minGuests: 80,
    maxGuests: 400,
    serviceDuration: 'Cả ngày',
    venueScope: 'Sảnh hội nghị tầng 2',
    defaultMenu: 'Corporate Buffet Menu',
    isFeatured: true,
    isActive: true,
    sortOrder: 2,
  },
  {
    name: 'Private Dining VIP',
    description:
      'Không gian riêng tư cho tiếp khách cao cấp với đầu bếp riêng và thực đơn cá nhân hóa.',
    basePrice: 18000000,
    imageUrl: 'https://images.unsplash.com/photo-1555244162-803834f70033',
    category: 'private_dining',
    features: [
      'Phòng ăn riêng chuẩn VIP',
      'Phục vụ 1:1 theo bàn',
      'Thực đơn cá nhân hóa',
    ],
    minGuests: 6,
    maxGuests: 20,
    serviceDuration: '2.5 tiếng',
    venueScope: 'Khu phòng VIP tầng 3',
    defaultMenu: 'Private Chef Tasting Menu',
    isFeatured: false,
    isActive: true,
    sortOrder: 3,
  },
  {
    name: 'Lễ kỷ niệm gia đình',
    description:
      'Gói phù hợp các dịp kỷ niệm, thôi nôi, mừng thọ với setup ấm cúng và chương trình ngắn gọn.',
    basePrice: 22000000,
    imageUrl: 'https://images.unsplash.com/photo-1532634922-8fe0b757fb13',
    category: 'celebration',
    features: [
      'Setup bàn tiệc theo nhóm gia đình',
      'Hỗ trợ màn hình trình chiếu ảnh',
      'Gợi ý timeline chương trình',
    ],
    minGuests: 30,
    maxGuests: 150,
    serviceDuration: '3 tiếng',
    venueScope: 'Sảnh Lotus',
    defaultMenu: 'Family Celebration Menu',
    isFeatured: false,
    isActive: true,
    sortOrder: 4,
  },
  {
    name: 'Workshop doanh nghiệp',
    description:
      'Gói workshop chuyên nghiệp cho đào tạo nội bộ, họp chiến lược và hoạt động team building trong nhà.',
    priceLabel: 'Từ 15.000.000 VND',
    imageUrl: 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d',
    category: 'corporate',
    features: [
      'Phòng họp tiêu chuẩn doanh nghiệp',
      'Projector và âm thanh hội thảo',
      'Tea-break 2 lần',
    ],
    minGuests: 20,
    maxGuests: 100,
    serviceDuration: '6 tiếng',
    venueScope: 'Meeting hall khu business',
    defaultMenu: 'Workshop Light Menu',
    isFeatured: false,
    isActive: true,
    sortOrder: 5,
  },
];
