export enum ErrorCode {
  // AUTHENTICATION ERRORS
  AUTH_USER_NOT_FOUND = 'AUTH_USER_NOT_FOUND',
  AUTH_WRONG_PASSWORD = 'AUTH_WRONG_PASSWORD',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID = 'AUTH_TOKEN_INVALID',
  AUTH_EMAIL_EXISTED = 'AUTH_EMAIL_EXISTED',

  // COURSE & SLIDE ERRORS
  PROGRAM_NOT_FOUND = 'PROGRAM_NOT_FOUND',
  SLIDE_NOT_FOUND = 'SLIDE_NOT_FOUND',
  LESSON_NOT_FOUND = 'LESSON_NOT_FOUND',

  // GAME ERRORS
  GAME_NOT_FOUND = 'GAME_NOT_FOUND',
  GAME_MAX_ATTEMPTS_REACHED = 'GAME_MAX_ATTEMPTS_REACHED',
  GAME_TIME_EXCEEDED = 'GAME_TIME_EXCEEDED',
  GAME_INVALID_SLIDE_TYPE = 'GAME_INVALID_SLIDE_TYPE',
  GAME_NO_CONFIG = 'GAME_NO_CONFIG',
  GAME_UNSUPPORTED_TYPE = 'GAME_UNSUPPORTED_TYPE',

  // SYSTEM & HTTP ERRORS
  BAD_REQUEST_VALIDATION = 'BAD_REQUEST_VALIDATION',
  UNAUTHORIZED_ACCESS = 'UNAUTHORIZED_ACCESS',
  FORBIDDEN_RESOURCE = 'FORBIDDEN_RESOURCE',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  TENANT_NOT_FOUND = 'TENANT_NOT_FOUND',
}
